In [3]:
# Sentiment Analysis - Book Example - Movie Reviews.ipynb
!pip install pyprind

In [4]:
#Import libraries
import pyprind
import pandas as pd
import os

In [9]:
basepath = 'C:\dev\Machine-Learning\SentimentAnalysis_Ch8\data'

In [10]:
labels = {'pos' : 1, 'neg': 0}
pbar = pyprind.ProgBar(50000)
df = pd.DataFrame()

In [12]:
for s in ('test','train'):
    for l in ('pos','neg'):
        path = os.path.join(basepath, s, l)
        for file in sorted(os.listdir(path)):
            with open(os.path.join(path, file), 'r', encoding='utf-8') as infile:
                txt = infile.read()
            df = df._append([[txt, labels[l]]], ignore_index=True)
            pbar.update()
df.columns = ['review', 'sentiment']

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:14:32


In [13]:
import numpy as np

In [14]:
np.random.seed(0)
df = df.reindex(np.random.permutation(df.index))

In [15]:
df.to_csv('movie_data.csv', index=False, encoding='utf-8')

In [16]:
df.to_csv('C:\dev\Machine-Learning\SentimentAnalysis_Ch8\movie_data.csv', index=False, encoding='utf-8')

In [19]:
df = pd.read_csv('C:\dev\Machine-Learning\SentimentAnalysis_Ch8\movie_data.csv', encoding='utf-8')
df.head(3)

review  sentiment
0  In 1974, the teenager Martha Moxley (Maggie Gr...          1
1  OK... so... I really like Kris Kristofferson a...          0
2  ***SPOILER*** Do not read this, if you think a...          0

In [20]:
df.shape

(50000, 2)

In [21]:
#Transforming words into feature vectors
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
count = CountVectorizer()

In [28]:
docs = np.array(['The sum is shining','The weather is sweet', 'The sun is shining, the weather is sweet,', 'and one and one is two'])

In [29]:
bag = count.fit_transform(docs)

In [26]:
bag

<4x10 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [30]:
print(count.vocabulary_)

{'the': 7, 'sum': 4, 'is': 1, 'shining': 3, 'weather': 9, 'sweet': 6, 'sun': 5, 'and': 0, 'one': 2, 'two': 8}


In [31]:
print(bag.toarray())

[[0 1 0 1 1 0 0 1 0 0]
 [0 1 0 0 0 0 1 1 0 1]
 [0 2 0 1 0 1 1 2 0 1]
 [2 1 2 0 0 0 0 0 1 0]]
